import Footer from "./footer/Footer";
import HeaderOffline from "./header/Header-offline";

interface Props {
    children: React.ReactNode;
    classMeta?: string;
}

const LayoutWithFooter = (props: Props) => {
    return ( 
    //     <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
        <main className="dark:bg-gray-900">
            <section>
                <HeaderOffline />
            </section>

            <section>{props.children}</section>

            <section>
                <Footer />
            </section>
        </main>
     );
}
 
export default LayoutWithFooter;