import '../../globals.css'
import type { AppProps } from 'next/app'
import { Dosis } from '@next/font/google'
import Head from 'next/head'

const dosis = Dosis({
  subsets: ['latin']
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={dosis.className}>
      <Head>
        <title>TECH CMR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </main>
  )
}
